"""add holding avg_cost and asset_class

Revision ID: a07d950d5d9c
Revises: a1b2c3d4e5f6
Create Date: 2026-07-04 16:10:36.332591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07d950d5d9c'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('holdings', 'quantity',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=False)
    op.alter_column('holdings', 'avg_cost',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=False)
    op.alter_column('holdings', 'asset_class',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'equity'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('holdings', 'asset_class',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'equity'::character varying"))
    op.alter_column('holdings', 'avg_cost',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=True)
    op.alter_column('holdings', 'quantity',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=True)
    # ### end Alembic commands ###
